// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GuiApp Wails 绑定结构体。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackToLogin 从 WebUI 返回登录窗口（可选功能，供托盘菜单使用）
 */
export function BackToLogin(): $CancellablePromise<void> {
    return $Call.ByID(2210097929);
}

/**
 * CheckForUpdates 触发更新检查，在自定义更新窗口中展示结果，
 * 并等待用户在窗口中点击"下载并安装"后才会真正下载、安装更新。
 * 供前端按钮和托盘菜单调用。
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1256446317);
}

/**
 * CompleteInit 在用户修正端口冲突后，由前端调用，完成后端初始化。
 */
export function CompleteInit(): $CancellablePromise<void> {
    return $Call.ByID(3843184923);
}

/**
 * EnterWebUI 由前端调用：切换到本地 WebUI 大窗，隐藏登录小窗。
 * 每次调用都会用 g.configPath 刷新 URL，确保切换配置后 admin 显示正确的配置路径。
 */
export function EnterWebUI(): $CancellablePromise<void> {
    return $Call.ByID(551937120);
}

/**
 * GetAPIKey 返回当前配置的 API Key，供本地 WebUI 页面通过 Wails binding 调用。
 */
export function GetAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(873040829);
}

/**
 * GetAppInfo 返回应用运行信息（含端口冲突检测）。
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1303911513);
}

/**
 * GetAutoStartEnabled 查询当前开机自启状态（供托盘菜单调用）。
 */
export function GetAutoStartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2283529356);
}

/**
 * GetCheckState 返回当前后端的检测进度状态，供灵动岛等前端页面调用
 */
export function GetCheckState(): $CancellablePromise<$models.CheckState> {
    return $Call.ByID(3279137383);
}

/**
 * GetConfigPath 返回当前生效配置文件的绝对路径。
 * 以函数引用形式传给 newCombinedAssetHandler，保证切换配置后注入值实时更新。
 */
export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1772900587);
}

/**
 * GetEnterNonce 生成一次性 nonce，用于 /gui/enter 安全跳转。
 */
export function GetEnterNonce(remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(3832583147, remember);
}

/**
 * GetListenPort 返回 Gin HTTP 服务监听的端口号（不含冒号），
 * 供 newCombinedAssetHandler 构造反向代理目标地址使用。
 */
export function GetListenPort(): $CancellablePromise<string> {
    return $Call.ByID(96953646);
}

/**
 * GetUpdateInfo 通过 Wails 内置更新器查询更新状态，返回给前端。
 */
export function GetUpdateInfo(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1712625151);
}

export function GetUpdateStatus(): $CancellablePromise<updater$0.UpdateStatus> {
    return $Call.ByID(3197368653);
}

/**
 * HideToTray 供前端"关闭按钮对话框"选择最小化时调用。
 */
export function HideToTray(): $CancellablePromise<void> {
    return $Call.ByID(171980759);
}

/**
 * IsBackendReady 动态查询后端是否已成功初始化并正在运行。
 */
export function IsBackendReady(): $CancellablePromise<boolean> {
    return $Call.ByID(4055968029);
}

/**
 * OpenAboutWindow 打开或聚焦「关于」独立窗口（单例模式）。
 */
export function OpenAboutWindow(): $CancellablePromise<void> {
    return $Call.ByID(3115421951);
}

/**
 * OpenAnalysisWindow 打开或聚焦「分析报告」独立窗口（单例模式）。
 * 通过 /gui/enter nonce 中转，自动完成 API Key 写入，无需用户手动登录。
 * OpenAnalysisWindow 打开或聚焦「分析报告」独立窗口（单例模式）。
 * 通过 /gui/enter nonce 中转，自动完成 API Key 写入，无需用户手动登录。
 */
export function OpenAnalysisWindow(): $CancellablePromise<void> {
    return $Call.ByID(2205529368);
}

/**
 * OpenBrandURL 在 Wails 无地址栏窗口中打开品牌 / 社交链接。
 */
export function OpenBrandURL(url: string, windowSize: string): $CancellablePromise<void> {
    return $Call.ByID(541730476, url, windowSize);
}

/**
 * OpenConfigFile 打开系统文件选择对话框，返回用户选择的配置文件路径。
 * 用户取消时返回空字符串（不返回错误）。
 */
export function OpenConfigFile(): $CancellablePromise<string> {
    return $Call.ByID(1547608438);
}

/**
 * OpenFilesWindow 打开或聚焦「内置文件」独立窗口（单例模式）。
 * 通过 /gui/enter nonce 中转，自动完成 API Key 写入，无需用户手动登录。
 */
export function OpenFilesWindow(): $CancellablePromise<void> {
    return $Call.ByID(3767068697);
}

/**
 * OpenInternalPage 在新窗口中打开内置 Web 页面（如 /files、/analysis）。
 * 通过 /gui/enter?n=<nonce>&redirect=<path> 中转，确保弹出窗口自动写入 API Key。
 */
export function OpenInternalPage(path: string, title: string, windowSize: string): $CancellablePromise<void> {
    return $Call.ByID(1633695184, path, title, windowSize);
}

/**
 * OpenSubLinksWindow 打开或聚焦「订阅链接」独立窗口（单例模式）。
 */
export function OpenSubLinksWindow(): $CancellablePromise<void> {
    return $Call.ByID(4239119837);
}

/**
 * OpenSubStoreWindow 打开或聚焦 Sub-Store 订阅管理独立窗口（单例模式）。
 */
export function OpenSubStoreWindow(): $CancellablePromise<void> {
    return $Call.ByID(2471289197);
}

/**
 * QuitApp 供前端"关闭按钮对话框"选择退出时调用。
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(1033637092);
}

/**
 * SetAutoStart 供前端 JS 绑定调用，切换开机自启。
 * 成功后同步更新托盘菜单 checkbox，保证两侧状态一致。
 */
export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(940964243, enabled);
}

/**
 * SetAutoStartEnabled 设置开机自启状态（供托盘菜单内部调用，不重复更新托盘 checkbox）。
 * 修复：原实现忽略了 enable 参数，总是调用 Enable()。
 */
export function SetAutoStartEnabled(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(197427528, enable);
}

/**
 * SetPorts 更新端口配置。
 */
export function SetPorts(httpPort: string, subStorePort: string): $CancellablePromise<void> {
    return $Call.ByID(3443572318, httpPort, subStorePort);
}

/**
 * ShowWindow 供前端主动调用，显示并聚焦主窗口。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(91192051);
}

/**
 * SwitchConfigFile 切换到用户重新选择的配置文件：
 *  1. 直接读取目标配置文件中的 api-key 并与用户输入比对（不影响当前运行的内核）；
 *  2. 密钥匹配后，关闭（Shutdown）当前正在运行的内核实例；
 *  3. 等待旧内核占用的 HTTP 端口完全释放；
 *  4. 以新配置文件重新初始化并启动内核（Initialize 内部已包含 InitConfigLoad）；
 *  5. 返回切换后的 AppInfo，前端据此刷新界面状态并调用 EnterWebUI 进入管理界面。
 * 
 * 密钥不匹配或步骤 1 失败时，当前内核保持不变。
 * 步骤 2–4 失败时旧内核已不可恢复，g.backend 置 nil，g.pendingInit 置 true，
 * 错误原样返回给前端展示，用户可重试或重启程序。
 */
export function SwitchConfigFile(path: string, enteredKey: string): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(3083586062, path, enteredKey);
}

/**
 * ValidateConfigKey 验证密钥，通过后返回一次性 nonce。
 */
export function ValidateConfigKey(enteredKey: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(2798811533, enteredKey, remember);
}

/**
 * ValidatePort 实时验证单个端口号合法性（格式 + 是否被占用）。
 * 返回空字符串表示端口格式正确且当前未被占用。
 */
export function ValidatePort(port: string): $CancellablePromise<string> {
    return $Call.ByID(2902552419, port);
}
