// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * APIProxy 是安卓端保存配置等所有 POST 类操作的核心解决方案：
 * 在应用进程内直接把请求灌入内核的 gin 路由器处理，完全不经过任何 socket/网络 I/O。
 * 
 * 根因：Android 的 WebResourceRequest API 从未暴露过 POST 请求体（Chromium 遗留问题，
 * 官方明确不会修复），导致任何经由 shouldInterceptRequest 拦截转发的 POST 请求，
 * 请求体到达 Go 侧时必然是空的（EOF）——这与"Windows/Linux/macOS 均正常，唯独安卓不行"
 * 的现象完全吻合，因为那几个平台的原生 WebView（WebView2/WebKitGTK/WKWebView）拦截层
 * 能拿到请求体，只有 Android 拿不到。
 * 
 * 通过 Wails 原生绑定（$Call.ByID，即生成的 bindings）调用本方法时，method/path/body
 * 是作为普通字符串参数经由 JS↔Go 原生桥直接传递的，从始至终都不是一次被拦截的网络请求，
 * 因此不受此限制影响，安卓上也能拿到完整的 body。
 * 
 * 返回值统一为 {"status": <int>, "body": <string>} 的 JSON 字符串，前端 sfetch 按普通
 * fetch 响应的方式解析即可。
 */
export function APIProxy(method: string, path: string, body: string): $CancellablePromise<string> {
    return $Call.ByID(2267284878, method, path, body);
}

export function BackToHome(): $CancellablePromise<void> {
    return $Call.ByID(1826000275);
}

/**
 * CopyToClipboard 将文本写入系统剪贴板。
 * 作为前端 navigator.clipboard 失败时的强力原生兜底。
 */
export function CopyToClipboard(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(3613982208, text);
}

/**
 * ExitApp 退出应用：先优雅关闭内核（ShutdownCore），再结束进程。
 * 不依赖任何 Java 层改动。结束进程前短暂等待，让异步投递的 stopService 先执行，
 * 避免 START_STICKY 的前台服务在进程退出后被系统重新拉起、残留通知。
 */
export function ExitApp(): $CancellablePromise<void> {
    return $Call.ByID(3950223045);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1303911513);
}

export function GetCheckState(): $CancellablePromise<$models.CheckState> {
    return $Call.ByID(3279137383);
}

/**
 * GetNetworkStatus 获取当前设备网络状态，返回 JSON (例如 {"connected":true,"type":"cellular"})
 */
export function GetNetworkStatus(): $CancellablePromise<string> {
    return $Call.ByID(1069548834);
}

/**
 * GetPowerStatus 获取当前设备电量状态，返回 JSON (例如 {"level":0.15,"charging":false,"lowPower":true})
 * state as {"level":0-1,"charging":bool,"lowPower":bool}. * /
 */
export function GetPowerStatus(): $CancellablePromise<string> {
    return $Call.ByID(507430917);
}

export function GetPublicInfo(): $CancellablePromise<$models.PublicInfo> {
    return $Call.ByID(2318748255);
}

export function GetSafeArea(): $CancellablePromise<$models.SafeArea> {
    return $Call.ByID(4144788850);
}

/**
 * GetUpdateInfo 供前端调用，获取更新数据并自动拼接内置反代服务器地址
 */
export function GetUpdateInfo(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1712625151);
}

/**
 * HapticFeedback 震动反馈
 */
export function HapticFeedback(hapticType: string): $CancellablePromise<void> {
    return $Call.ByID(2383052482, hapticType);
}

/**
 * MarkAPIKeyManual 由前端在手动编辑 API Key 并保存成功后调用，标记本次
 * 运行期间密钥已不再是随机生成的。GUI_KEY_IS_RANDOM 环境变量只在进程启动
 * 时探测一次，不会随配置文件的变化而自动刷新，所以这一步是必要的——否则
 * "随机密钥"提示图标会一直显示，直到应用重启为止。
 */
export function MarkAPIKeyManual(): $CancellablePromise<void> {
    return $Call.ByID(412753314);
}

/**
 * OpenInBrowser 调用 Wails 3 Mobile API 在系统浏览器中打开外部链接。
 */
export function OpenInBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(3639668739, url);
}

/**
 * Platform 返回所属平台
 */
export function Platform(): $CancellablePromise<string> {
    return $Call.ByID(1851100933);
}

/**
 * SaveConfig 保留作为向后兼容的绑定入口（例如首页如果还想直接调用它）。
 * 内部不再是裸的 os.WriteFile，而是改为走 APIProxy 调用真正的 /api/config
 * 处理逻辑——这样保存配置时才会附带触发 Sub-Store 后台同步等完整副作用，
 * 和桌面端 web 面板走 POST /api/config 的行为完全一致。
 * webui 的 admin.js 建议直接调用 window.WailsBridge.APIProxy("POST","/api/config",...)，
 * 这个方法留给可能还会用到简化调用形式的地方。
 */
export function SaveConfig(content: string): $CancellablePromise<string> {
    return $Call.ByID(2745871521, content);
}

/**
 * SetKeepAwake 检测运行期间保持屏幕常亮，避免手机自动锁屏后检测任务被系统
 * 限流甚至暂停。注意：这只在应用处于前台可见时有效；真正的"切到后台也保证
 * 跑完"由 service_android.go 的 StartForegroundService/StopForegroundService
 * 负责（Android 专属能力，非安卓平台见 service_other.go 的空实现）。
 */
export function SetKeepAwake(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2858937814, enabled);
}

/**
 * SetStatusBarAppearance 根据当前是否为深色主题，同步系统状态栏的图标颜色与背景色。
 */
export function SetStatusBarAppearance(isDark: boolean): $CancellablePromise<void> {
    return $Call.ByID(737564367, isDark);
}

/**
 * ShareLink 调起系统原生分享面板（Android 分享 Intent / iOS
 * UIActivityViewController），把一段文本/链接分享给手机上安装的其他 App——
 * 比如把订阅链接分享到 IM、笔记，或是能接收订阅链接的其他代理客户端。
 * 用的是 application.Mobile.Share，跨 iOS/Android 通用；桌面端是空操作，
 * 不需要额外判断平台。
 */
export function ShareLink(text: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(3439861457, text, url);
}

/**
 * ShutdownCore 供前端「退出应用」调用：先关闭后端内核，再由 Java 层结束进程。
 * 
 * 顺序：
 *  1. 停止前台服务（否则通知会残留）
 *  2. 调用 core.Shutdown()：取消 ctx（Sub-Store 等子服务退出）、停止定时任务与配置监听、
 *     优雅关闭 HTTP 服务器（内部最长等待 5 秒，另有 500ms 清理等待）
 * 
 * 整体设置 8 秒上限，防止个别任务卡死导致"退出"按钮一直无响应。
 * 返回 true 表示内核已完整关闭，false 表示超时（调用方仍应继续退出流程）。
 * 多次调用安全：只会真正关闭一次。
 */
export function ShutdownCore(): $CancellablePromise<boolean> {
    return $Call.ByID(68459767);
}

/**
 * StartForegroundService 在非安卓平台是空操作。前台服务是安卓专属概念，
 * 但前端（App.tsx）是桌面/iOS/安卓共用的同一份代码，会在检测开始时无条件
 * 调用这个方法，所以这里必须留一个空实现，否则桌面/iOS 构建时绑定里根本
 * 没有这个方法，前端调用会直接报错。
 */
export function StartForegroundService(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(3142360390, title, body);
}

/**
 * StopForegroundService 在非安卓平台是空操作，理由同上。
 */
export function StopForegroundService(): $CancellablePromise<void> {
    return $Call.ByID(4119988542);
}
