// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppInfo {
    "apiKey": string;
    "listenPort": string;
    "subStorePort": string;
    "subStorePath": string;
    "singBoxOldVer": string;
    "singBoxLatestVer": string;
    "keyIsRandom": boolean;
    "isFirstRun": boolean;
    "configPath": string;
    "pendingInit": boolean;
    "initErr": string;

    /**
     * GuiVersion 桌面客户端版本（ldflags 注入，如 "v1.2.0"）
     */
    "guiVersion": string;

    /**
     * CoreVersion 内核版本+短提交哈希（如 "v2.5.4@7c23868"）
     */
    "coreVersion": string;
}

export interface CheckState {
    "isChecking": boolean;
    "stepName": string;
    "available": number;
    "progress": number;
    "proxyCount": number;
    "lastResult": string;
}

export interface PublicInfo {
    "listenPort": string;
    "subStorePort": string;
    "subStorePath": string;
    "guiVersion": string;
    "coreVersion": string;
}

export interface SafeArea {
    "top": number;
    "bottom": number;
    "left": number;
    "right": number;
}
